name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image and publish to GitHub Packages
      run: |
        VERSION=$(date +%s)
        docker build . --file Dockerfile --tag docker.pkg.github.com/kaylangan/calculator/app:${VERSION}
        docker login docker.pkg.github.com --username kaylangan --password ${{ secrets.GITHUB_TOKEN }}
        docker push docker.pkg.github.com/kaylangan/calculator/app:${VERSION}
      
